spring.data.mongodb.url=mongodb+srv://lordgrim636_db_user:0toJZgflTF9APBLG@journalappapplication.j3j4eu2.mongodb.net/?appName=JournalAppApplication
spring.data.mongodb.port=27017
spring.data.mongodb.database=database
spring.data.mongodb.auto-index-creation=true
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

#spring.profiles.active=dev

#logging.level.root=ERROR

weather_api=a04ced88b62d4e3c8d48e1a455976076

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=birenderpalsingh04@gmail.com
spring.mail.password=ojtk plzx glub yqdh

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
