spring.data.url=mongodb+srv://lordgrim636_db_user:0toJZgflTF9APBLG@journalappapplication.j3j4eu2.mongodb.net/?appName=JournalAppApplication
server.port=8081
server.servlet.context-path=/start
spring.data.mongodb.database=database
spring.data.mongodb.auto-index-creation=true
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true



